Desarrollo
AJimenezHolguin/Hotels pull request #3
Opened 2023-08-14 06:39 UTC by AJimenezHolguin

Se realiza filtro de fechas, se ajusta boton clear para su correcto funcionamiento, se deja mensaje informando cuando no hay hoteles disponibles.

2023-08-14 14:09 UTC, DanielCalleCO commented
Anderson, tienes un problemas con los logos de Chile y Uruguay que estás usando, te salen así:

![image](https://github.com/AJimenezHolguin/Hotels/assets/100431019/652a14fc-33ff-48dc-81d3-d310b270a738)

2023-08-14 14:12 UTC, DanielCalleCO requested changes
Los filtros de fechas están geniales! Te felicito mi hermano. Verifica el filtro de sizes y creo que podemos aprobar (te dejé un comentario de los logos de las banderas de los paises)

2023-08-14 14:12 UTC, DanielCalleCO commented on index.js
>  const resetBtn = document.getElementById("filter");
el botón CLEAR no está borrando la info del filtro sizes... e incluso ese filtro no está funcionando

2023-08-14 15:46 UTC, AJimenezHolguin commented on index.js
>  const resetBtn = document.getElementById("filter");
Buenos días si profe el filtro de sizes no lo hice porque no lo solicitaba para el reto ya que en la planing que se dio al inicio Daniel mayo decía eso el resto de la página la ibamos a terminar con react, de igual forma voy a realizar el filtro de sizes y ajustar los logos de chile y uruguay pero ahi para que me tenga en cuenta profe que practicamente ya realice este reto jejejej se le quiere hombre gracias por que se que quieres que hagamos las cosas de manera profesional!!!

2023-08-15 00:28 UTC, DanielCalleCO approved these changes

2023-08-15 00:51 UTC, merged